### ISSUE TITLE
Middleware usage has changed

### ISSUE THREAD

**Issue by murrple-1** [aminalaee/sqladmin#270]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

The docs as the currently stand are wrong: https://aminalaee.dev/sqladmin/authentication/#authentication-backend

Instead of passing in a `list[starlette.middleware.Middleware]` to `sqladmin.Admin(middlewares=)`, one passes in a `list[Callable]`.

If this is "correct" behaviour going forward, then just the docs need updating.

Otherwise, this may be a regression.

In my opinion, this is inferior, just because one can no longer pass `options` to the middleware. But that can be worked around by subclassing the middleware you want to pass options to, and defining a custom `__init__()` function.

### Steps to reproduce the bug

```python
from sqladmin import Admin, ModelView
from starlette.applications import Starlette
from starlette.requests import Request

# AuthenticationMiddleware explained in Starlette docs

middlewares = [
    Middleware(AuthenticationMiddleware, backend=BasicAuthBackend())
]

app = Starlette()
admin = Admin(app=app, engine=engine, middlewares=middlewares)


class AuthModelView(ModelView):
    def is_accessible(self, request: Request) -> bool:
        # With Authentication backend you can now access request.user.
        if request.user.is_authenticated:
            return True
        return False
```

### Expected behavior

Middleware should work.

### Actual behavior

```
Traceback (most recent call last):
   File "/venv/bin/daphne", line 8, in <module>
     sys.exit(CommandLineInterface.entrypoint())
   File "/venv/lib/python3.10/site-packages/daphne/cli.py", line 170, in entrypoint
     cls().run(sys.argv[1:])
   File "/venv/lib/python3.10/site-packages/daphne/cli.py", line 232, in run
     application = import_by_path(args.application)
   File "/venv/lib/python3.10/site-packages/daphne/utils.py", line 12, in import_by_path
     target = importlib.import_module(module_path)
   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "/code/./myapp/main.py", line 32, in <module>
     admin = Admin(
   File "/venv/lib/python3.10/site-packages/sqladmin/application.py", line 321, in __init__
     self.admin.add_middleware(middleware)
   File "/venv/lib/python3.10/site-packages/starlette/applications.py", line 169, in add_middleware
     self.middleware_stack = self.build_middleware_stack()
   File "/venv/lib/python3.10/site-packages/starlette/applications.py", line 103, in build_middleware_stack
     app = cls(app=app, **options)
 TypeError: 'Middleware' object is not callable
```

### Environment

SQLAdmin: commit `ad1fa05`
Python: 3.10

**Comment by aminalaee** [comment]
Hey, thanks for checking this, you're right.

Now I've prepared the fix to keep it the same as before but fix this issue: https://github.com/aminalaee/sqladmin/pull/268
