### ISSUE TITLE
Cannot override list.html

### ISSUE THREAD

**Issue by patrykko-intel** [aminalaee/sqladmin#299]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I'm trying to change list.html view. I copied original list.html file from 0.4.0 version and placed it in templates folder according to instruction: https://aminalaee.dev/sqladmin/working_with_templates/#replacing-templates
I can confirm that sqladmin sees my file, but it doesn't work.
I got the following error:

Traceback (most recent call last):
  File ".../venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File ".../venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File ".../venv/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File ".../venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File ".../lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File ".../venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File ".../venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 57, in __call__
    task_group.cancel_scope.cancel()
  File ".../venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File ".../venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 30, in coro
    await self.app(scope, request.receive, send_stream.send)
  File ".../venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File ".../venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File ".../venv/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File ".../venv/lib/python3.8/site-packages/starlette/routing.py", line 408, in handle
    await self.app(scope, receive, send)
  File ".../venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File ".../venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File ".../venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File ".../venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File ".../venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File ".../venv/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File ".../venv/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/root/maestro-os-delivery/osd-portal/venv/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File ".../venv/lib/python3.8/site-packages/sqladmin/application.py", line 267, in list
    return self.templates.TemplateResponse(model_admin.list_template, context)
  File ".../venv/lib/python3.8/site-packages/starlette/templating.py", line 87, in TemplateResponse
    return _TemplateResponse(
  File "...venv/lib/python3.8/site-packages/starlette/templating.py", line 33, in __init__
    content = template.render(context)
  File ".../venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File ".../venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "templates/custom_list.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File ".../venv/lib/python3.8/site-packages/sqladmin/templates/layout.html", line 1, in top-level template code
    {% extends "base.html" %}
  File ".../venv/lib/python3.8/site-packages/sqladmin/templates/base.html", line 15, in top-level template code
    {% block body %}
  File .../venv/lib/python3.8/site-packages/sqladmin/templates/layout.html", line 49, in block 'body'
    {% block content %} {% endblock %}
  File "templates/custom_list.html", line 6, in block 'content'
    <h3 class="card-title">{{ model_view.name_plural }}</h3>
  File ".../venv/lib/python3.8/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'model_view' is undefined

### Steps to reproduce the bug

- create templates folder in project
- copy list.html file into that folder

### Expected behavior

It should work the same way as it works without templates/list.html file.

### Actual behavior

It ends with error.

### Environment

- Windows 10, Python 3.8, sqladmin 0.4.0

**Comment by aminalaee** [comment]
Hey,
I can't seem to reproduce this.

Can you share your templates content and structure and maybe share them as a gist?

**Comment by patrykko-intel** [comment]
I solve the issue. I didn't place the templates folder in a root. I made a mistake because I've got two root sources in my project. When I placed it in a root of my project, everything start working,
