### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'undefined' on "get_column_python_type" function.

### ISSUE THREAD

**Issue by vimevim** [aminalaee/sqladmin#393]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Hello

At first I noticed it on a table with many to many relationships but I kept trying to fix the problem, nothing good. I tried to reproduce the problem with a table that doesn't have a relationship, the thing gave me these errors:

I have this traceback coming up whenever I edit a model

```traceback
Traceback (most recent call last):
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\routing.py", line 66, in 
app
    response = await func(request)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\sqladmin\authentication.py", line 56, in wrapper_decorator
    return await func(*args, **kwargs)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\sqladmin\application.py", line 461, in edit
    model = await model_view.get_model_by_pk(request.path_params["pk"])
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\sqladmin\models.py", line 825, in get_model_by_pk
    pk_value = get_column_python_type(self.pk_column)(value)
ValueError: invalid literal for int() with base 10: 'undefined'
```

I have this traceback coming up whenever I click on the "view" button.

```traceback
Traceback (most recent call last):
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\starlette\routing.py", line 66, in 
app
    response = await func(request)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\sqladmin\authentication.py", line 56, in wrapper_decorator
    return await func(*args, **kwargs)
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\sqladmin\application.py", line 377, in details
    model = await model_view.get_model_by_pk(request.path_params["pk"])
  File "C:\Users\11K\AppData\Local\pypoetry\Cache\virtualenvs\my-application-blabla-3.8\lib\site-packages\sqladmin\models.py", line 825, in get_model_by_pk
    pk_value = get_column_python_type(self.pk_column)(value)
ValueError: invalid literal for int() with base 10: 'undefined'
```

### Steps to reproduce the bug

model.py

```py
# all imports are well.
class ErrorLogs(Base):
    __tablename__ = "error_logs"
    id = Column(Integer, primary_key=True)
    date_created = Column(DateTime, default=datetime.datetime.utcnow)
    date_updated = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)
    error_type = Column(Enum(ErrorTypes), nullable=False)
    error = Column(String)
    traceback = Column(String)
    details = Column(JSON)
```

admin.py
```py
# all imports are well.
class ErrorLogsAdmin(ModelView, model=models.ErrorLogs):
    column_list = [
        models.ErrorLogs.id, 
        models.ErrorLogs.date_created, 
        models.ErrorLogs.date_updated, 
        models.ErrorLogs.error_type, 
        models.ErrorLogs.error, 
        models.ErrorLogs.traceback, 
        ]
    column_searchable_list = [
        models.ErrorLogs.error_type,
        models.ErrorLogs.traceback,
        ]
    column_sortable_list = [
        models.ErrorLogs.id, 
        models.ErrorLogs.date_created, 
        models.ErrorLogs.date_updated, 
        models.ErrorLogs.error_type, 
        models.ErrorLogs.traceback
        ]
    column_formatters = {
        models.ErrorLogs.date_created: lambda m, a: m.date_created.strftime("%Y-%m-%d %H:%M:%S"),
        models.ErrorLogs.date_updated: lambda m, a: m.date_created.strftime("%Y-%m-%d %H:%M:%S"),
        models.ErrorLogs.error_type: lambda m, a: models.ErrorTypesMap[m.error_type],

        }
    column_default_sort = [
        (models.ErrorLogs.date_created, True), 
        (models.ErrorLogs.date_updated, True)
        ]
    column_labels = {
        models.ErrorLogs.id: "ID",
        models.ErrorLogs.date_created: "Date Created",
        models.ErrorLogs.date_updated: "Date Updated",
        models.ErrorLogs.error_type: "Error Type",
        models.ErrorLogs.error: "Error",
        models.ErrorLogs.traceback: "Traceback",
        models.ErrorLogs.details: "Details",
        }
    name = "Error Log"
    name_plural = "Error Logs"
    icon = "fa fa-exclamation-triangle"
    can_create = True # Will be False in production
    can_edit = True # Will be False in production
    can_delete = True # Will be False in production
    can_view_details = True
```

### Environment

- Windows 10
- Python 3.8.8
- fastapi = "0.88.0"
- sqladmin = "0.8.0"
- SQLAlchemy = "1.4.45"

### Additional context

I found out that Firefox client sends a second request for most of the time:
```console
INFO:     127.0.0.1:52432 - "GET /error-logs/list HTTP/1.1" 200 OK
INFO:     127.0.0.1:52432 - "GET /error-logs/undefined HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:52432 - "GET /error-logs/edit/1 HTTP/1.1" 200 OK
INFO:     127.0.0.1:52432 - "GET /error-logs/edit/undefined HTTP/1.1" 500 Internal Server Error
```
But the problem doesn't exists when using Chrome.

_No response_

**Comment by vimevim** [comment]
Problem is probably about my Firefox or some extension I use. But it's better to implement a logic or an error handler for this "/edit/undefined" or "/undefined" endpoints.
