### ISSUE TITLE
Using `wtforms.fields.FieldList` in `form_overrides` raises `TypeError`

### ISSUE THREAD

**Issue by FFX01** [aminalaee/sqladmin#412]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I am using FastAPI with SQLModel as my ORM. I have a model where one of the fields is a list of strings. In my postgresql database this is stored in an ARRAY column. I would like to render this field as a list of `StringField`s. However, when attempting to do so via the `ModelView.form_overrides` attribute, I get a `TypeError`.

### Steps to reproduce the bug

Here is a truncated version of my code:
```python
# models.py

class Brand(SQLModel, table=True):
    __tablename__ = 'brands'

    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(max_length=255)
    features: Optional[List[str]] = Field(
        sa_column=Column(postgresql.ARRAY(String(length=255))),
        default=None
    )
```

```python
# admin.py

class BrandAdmin(ModelView, model=models.Brand):
    form_overrides = {
        'features': FieldList(StringField())
    }
```

### Expected behavior

I would expect the form to render the `features` field as a list of text input boxes.

### Actual behavior

When visiting the edit view, the code throws a `TypeError`. I believe this is because `issubclass` does not consider `wtforms.fields.FieldList` to be ta class, which it definitely is. The traceback is listed below.

### Debugging material

```bash
nebula-api-1  | Traceback (most recent call last):
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
nebula-api-1  |     result = await app(self.scope, self.receive, self.send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
nebula-api-1  |     return await self.app(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
nebula-api-1  |     raise exc from None
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 78, in __call__
nebula-api-1  |     await self.app(scope, inner_receive, inner_send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
nebula-api-1  |     await super().__call__(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
nebula-api-1  |     await self.middleware_stack(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
nebula-api-1  |     raise exc
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
nebula-api-1  |     await self.app(scope, receive, _send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
nebula-api-1  |     await self.app(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
nebula-api-1  |     raise exc
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
nebula-api-1  |     await self.app(scope, receive, sender)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
nebula-api-1  |     raise e
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
nebula-api-1  |     await self.app(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
nebula-api-1  |     await route.handle(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/routing.py", line 418, in handle
nebula-api-1  |     await self.app(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
nebula-api-1  |     await self.middleware_stack(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
nebula-api-1  |     raise exc
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
nebula-api-1  |     await self.app(scope, receive, _send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
nebula-api-1  |     raise exc
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
nebula-api-1  |     await self.app(scope, receive, sender)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
nebula-api-1  |     await route.handle(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
nebula-api-1  |     await self.app(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
nebula-api-1  |     response = await func(request)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/sqladmin/authentication.py", line 56, in wrapper_decorator
nebula-api-1  |     return await func(*args, **kwargs)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/sqladmin/application.py", line 465, in edit
nebula-api-1  |     Form = await model_view.scaffold_form()
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/sqladmin/models.py", line 1005, in scaffold_form
nebula-api-1  |     return await get_model_form(
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/sqladmin/forms.py", line 536, in get_model_form
nebula-api-1  |     field = await converter.convert(
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/sqladmin/forms.py", line 287, in convert
nebula-api-1  |     assert issubclass(override, Field)
nebula-api-1  | TypeError: issubclass() arg 1 must be a class
```

### Environment

- `python:3.8-slim` docker container running on MacOS Monterrey 12.2.1
- Python 3.8
- sqladmin version 0.8.0
- sqlmodel version 0.0.8
- fastapi version 0.78.0

### Additional context

I believe this is either a bug or an unsupported feature. If this feature is unsupported, I did not see it mentioned anywhere in the documentation. I'll be happy to provide any additional required information. 

I'm not actually 100% if `wtforms.fields.FieldList` will actually work for my use case, but it doesn't seem that my use case is related to this error.

**Comment by aminalaee** [comment]
Hey, I think this should've worked out of the box, it's missing some implementation, I will take a look.

**Comment by FFX01** [comment]
@aminalaee 

Thank you for taking a look at this. Let me know if you need any more information.

**Comment by FFX01** [comment]
I performed a little bit more research using the shell:

```python
In [1]: from wtforms.fields import FieldList

In [2]: import inspect

In [3]: inspect.getmro(FieldList)
Out[3]: (wtforms.fields.list.FieldList, wtforms.fields.core.Field, object)

In [4]: from wtforms.fields import StringField

In [5]: inspect.getmro(StringField)
Out[5]: (wtforms.fields.simple.StringField, wtforms.fields.core.Field, object)

In [6]: from wtforms.fields import Field

In [7]: inspect.getmro(Field)
Out[7]: (wtforms.fields.core.Field, object)

In [8]: issubclass(FieldList, Field)
Out[8]: True
```

I was curious why calling `issubclass` in the shell resulted in the expected output while `issubclass` called in the sqladmin code resulted in the incorrect output, so I dug into sqladmin's source a little bit. I created a small test function in my shell to emulate the way in which `issubclass` is called.

```python
In [12]: def convert(override: Optional[Type[Field]] = None):
    ...:     print(inspect.getmro(override))
    ...:     assert issubclass(override, Field)
    ...: 

In [13]: convert(FieldList)
(<class 'wtforms.fields.list.FieldList'>, <class 'wtforms.fields.core.Field'>, <class 'object'>)
```

This confirmed there wasn't any weird type shadowing or anything happening because of the annotations.

So, I then thought about how this method is called and what exactly is getting passed in as the `override` argument. I took a look at `get_model_form` which gets the value of the form override by calling `.get` on the dict passed to it as the `form_overrides` argument if the field name is present in the `attributes` dictionary. There's not a lot that could go wrong here, so I went looking for where the `get_model_form` function is called.

`get_model_form` is called by `ModelView.scaffold_form` and the  `form_overrides` argument contains the value of `self.form_overrides`. There also didn't seem to be many possible errors in this workflow either.

I then decided to emulate some of this behavior via an example class in the shell:

```python
In [16]: class Thing:
    ...:     form_overrides: ClassVar[Dict[str, Type[Field]]] = {}
    ...: 

In [17]: class MyThing(Thing):
    ...:     form_overrides = {'field1': FieldList()}
    ...: 

In [18]: convert(MyThing.form_overrides['field1'])
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[18], line 1
----> 1 convert(MyThing.form_overrides['field1'])

Cell In[12], line 2, in convert(override)
      1 def convert(override: Optional[Type[Field]] = None):
----> 2     print(inspect.getmro(override))
      3     assert issubclass(override, Field)

File /usr/local/lib/python3.8/inspect.py:489, in getmro(cls)
    487 def getmro(cls):
    488     "Return tuple of base classes (including cls) in method resolution order."
--> 489     return cls.__mro__

AttributeError: 'UnboundField' object has no attribute '__mro__'

In [19]: inspect.getmro(FieldList())
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[19], line 1
----> 1 inspect.getmro(FieldList())

File /usr/local/lib/python3.8/inspect.py:489, in getmro(cls)
    487 def getmro(cls):
    488     "Return tuple of base classes (including cls) in method resolution order."
--> 489     return cls.__mro__

AttributeError: 'UnboundField' object has no attribute '__mro__'
```

Which then lead me to try:

```python
In [20]: issubclass(FieldList(), Field)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[20], line 1
----> 1 issubclass(FieldList(), Field)

TypeError: issubclass() arg 1 must be a class
```

Aha! `FieldList()` isn't a class, it's a class instance. That's the reason for the error. To confirm, I modified my code to:

```python
class BrandAdmin(ModelView, model=Brand):
    form_overrides = {
        'features': fields.FieldList
    }
```

And I received a different traceback:

```bash
nebula-api-1  | Traceback (most recent call last):
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
nebula-api-1  |     result = await app(self.scope, self.receive, self.send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
nebula-api-1  |     return await self.app(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
nebula-api-1  |     raise exc from None
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 78, in __call__
nebula-api-1  |     await self.app(scope, inner_receive, inner_send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
nebula-api-1  |     await super().__call__(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
nebula-api-1  |     await self.middleware_stack(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
nebula-api-1  |     raise exc
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
nebula-api-1  |     await self.app(scope, receive, _send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
nebula-api-1  |     await self.app(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
nebula-api-1  |     raise exc
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
nebula-api-1  |     await self.app(scope, receive, sender)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
nebula-api-1  |     raise e
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
nebula-api-1  |     await self.app(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
nebula-api-1  |     await route.handle(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/routing.py", line 418, in handle
nebula-api-1  |     await self.app(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
nebula-api-1  |     await self.middleware_stack(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
nebula-api-1  |     raise exc
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
nebula-api-1  |     await self.app(scope, receive, _send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
nebula-api-1  |     raise exc
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
nebula-api-1  |     await self.app(scope, receive, sender)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
nebula-api-1  |     await route.handle(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
nebula-api-1  |     await self.app(scope, receive, send)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
nebula-api-1  |     response = await func(request)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/sqladmin/authentication.py", line 56, in wrapper_decorator
nebula-api-1  |     return await func(*args, **kwargs)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/sqladmin/application.py", line 469, in edit
nebula-api-1  |     "form": Form(obj=model),
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
nebula-api-1  |     return type.__call__(cls, *args, **kwargs)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/wtforms/form.py", line 280, in __init__
nebula-api-1  |     super().__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/wtforms/form.py", line 48, in __init__
nebula-api-1  |     field = meta.bind_field(self, unbound_field, options)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/wtforms/meta.py", line 28, in bind_field
nebula-api-1  |     return unbound_field.bind(form=form, **options)
nebula-api-1  |   File "/nebula/lib/python3.8/site-packages/wtforms/fields/core.py", line 395, in bind
nebula-api-1  |     return self.field_class(*self.args, **kw)
nebula-api-1  | TypeError: __init__() missing 1 required positional argument: 'unbound_field'
```

This error is from wtforms because `FieldList` requires another `Field` as a parameter.

All this to come to the conclusion that: an instantiated `Field` class cannot be passed into `form_overrides` because it will fail the `issubclass(override, Field)` assertion.

Just to be extra sure, I modified my code again to test it with an instantiated simple wtforms field:
```python
class BrandAdmin(ModelView, model=Brand):
    form_overrides = {
        'features': fields.StringField()
    }
```

And i got the same error and traceback as in the OP of this issue.

After doing all of this, I realized I could have just looked at the line below the assertion to see what was going on. The field cannot be instantiated when passed as an override because it needs to be instantiated in the convert function in order to pass in the necessary kwargs. I believe it is done this way to account for relationship fields. 

So, as it stands, it is impossible to use any compound fields in the form overrides. As far as solutions go, maybe moving the relationship field check to earlier in the flow or something of that nature might work. However, that may break other things.

As for my current use case, I guess I will create a custom form class and use that.

**Comment by aminalaee** [comment]
Thanks again for checking this, yes you are right.
But I was thinking that the ARRAY type should just be supported out of the box, so you won't have this issue at all.

**Comment by aminalaee** [comment]
Feel free to take a look at that PR as one step still needs to be fixed.

**Comment by FFX01** [comment]
I took a look at the PR. Looks like a converter needed to be explicitly defined for the column type. Did you need me to do anything in order to get this into the next release?

**Comment by aminalaee** [comment]
No, I need to fix the edit page, otherwise looks good.

**Comment by randbytes** [comment]
I think I have the same problem
`form_overrides = {'groupName'=SelectMultipleField("Select", choices=[("1", "1")])} # assert error`
What I'm doing wrong?

**Comment by aminalaee** [comment]
Without knowing about your models and example it's really hard to say. Please open a separate discussion or issue with minimal example.
