### ISSUE TITLE
Not working with the latest fastapi 0.94.1 release

### ISSUE THREAD

**Issue by mavroprovato** [aminalaee/sqladmin#447]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Hello,

I am using sqladmin with my project, the source of which you can find here: https://github.com/mavroprovato/fuelpricesgr

When I try to update to fastapi version 0.93.0 or later, the admin crashes. With previous versions it works. I have attached the stack trace.

### Debugging material

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 86, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/sqladmin/authentication.py", line 56, in wrapper_decorator
    return await func(*args, **kwargs)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/sqladmin/application.py", line 367, in list
    return self.templates.TemplateResponse(model_view.list_template, context)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/templating.py", line 113, in TemplateResponse
    return _TemplateResponse(
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/starlette/templating.py", line 39, in __init__
    content = template.render(context)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/sqladmin/templates/list.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/sqladmin/templates/layout.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/sqladmin/templates/base.html", line 17, in top-level template code
    {% block body %}
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/sqladmin/templates/layout.html", line 65, in block 'body'
    {% block content %} {% endblock %}
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/sqladmin/templates/list.html", line 102, in block 'content'
    <a href="#" data-name="{{ model_view.name }}" data-pk="{{ model_view.get_prop_value(row, model_view.pk_column) }}" data-url="{{ model_view._url_for_delete(request, row) }}" data-bs-toggle="modal" data-bs-target="#modal-delete" title="Delete">
  File "/home/kostas/.cache/pypoetry/virtualenvs/fuelpricesgr-BkUJlFTl-py3.10/lib/python3.10/site-packages/sqladmin/models.py", line 758, in _url_for_delete
    return url + "?" + query_params
TypeError: unsupported operand type(s) for +: 'URL' and 'str'

### Environment

OS: Ubuntu 22.04.2
Python : 3.10
SQLAdmin: 0.9.0

**Comment by aminalaee** [comment]
Hi,
Yes this is already fixed in https://github.com/aminalaee/sqladmin/pull/444
I will do a release tomorrow to allow this fix be used.

**Comment by mavroprovato** [comment]
Hello @aminalaee and thanks for the quick response! Sorry, I only checked the open issues and not PRs

**Comment by aminalaee** [comment]
No worries, this is will be in v0.10.0 today.
