### ISSUE TITLE
ImageType support issue

### ISSUE THREAD

**Issue by graky** [aminalaee/sqladmin#470]
### Checklist

- [x] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

According to the [documentation](https://aminalaee.dev/sqladmin/working_with_files/l), sqladmin supports ImageType. However, I encountered an issue when using it in my models.

My models are defined as follows:
   
```
class MessageToSend(Base):
    __tablename__ = "message_to_send"
    id = Column(sqlalchemy.Integer, primary_key=True, index=True)
    message_text = Column(sqlalchemy.Text, nullable=True)
    datetime_to_send = Column(sqlalchemy.DateTime, nullable=True)
    instant_send = Column(sqlalchemy.Boolean, default=False)
    images = relationship(
        "ImagesToSend",
        cascade="all,delete",
        back_populates="message",
    )
    files = relationship(
        "FileToSend",
        cascade="all,delete",
        back_populates="message",
    )

    def __repr__(self):
        return f"{self.id}, {self.message_text[:30]}"

class ImagesToSend(Base):
    __tablename__ = "image_to_send"
    id = Column(sqlalchemy.Integer, primary_key=True, index=True)
    image = Column(ImageType(storage=FileSystemStorage(path="media/images/")))
    message_id = Column(
        sqlalchemy.Integer,
        ForeignKey(MessageToSend.id, ondelete="CASCADE"),
    )
    message = relationship("MessageToSend", foreign_keys="ImagesToSend.message_id")


class FileToSend(Base):
    __tablename__ = "file_to_send"
    id = Column(sqlalchemy.Integer, primary_key=True, index=True)
    file = Column(FileType(storage=FileSystemStorage(path="media/files/")))
    message_id = Column(
        sqlalchemy.Integer,
        ForeignKey(MessageToSend.id, ondelete="CASCADE"),
    )
    message = relationship("MessageToSend", foreign_keys="FileToSend.message_id")


```
And the corresponding ModelView classes:

```
class MessageToSendAdmin(ModelView, model=MessageToSend):
    column_list = [MessageToSend.id, MessageToSend.datetime_to_send]

class ImagesAdmin(ModelView, model=ImagesToSend):
    column_list = [ImagesToSend.id, ImagesToSend.message_id]

class FilesAdmin(ModelView, model=FileToSend):
    column_list = [FileToSend.id, FileToSend.message_id]

```

While FileType works as expected, I encounter the following error when accessing the ImagesToSend edit page:

`sqladmin.exceptions.NoConverterFound: Could not find field converter for column image (<class 'sqlalchemy_fields.types.image.ImageType'>).`

I have reviewed the source code but could not find a suitable converter. Is this an issue with my implementation or a misunderstanding of the documentation? Any guidance or clarification would be appreciated

### Debugging material

Full traceback: 

INFO:     127.0.0.1:56373 - "GET /images-to-send/create HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\middleware\base.py", line 109, in __call__
    await response(scope, receive, send)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\middleware\base.py", line 134, in stream_response
    return await super().stream_response(send)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\middleware\base.py", line 98, in body_stream
    raise app_exc
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\middleware\sessions.py", line 86, in __call__
    await self.app(scope, receive, send_wrapper)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\sqladmin\authentication.py", line 60, in wrapper_decorator
    return await func(*args, **kwargs)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\sqladmin\application.py", line 429, in create
    Form = await model_view.scaffold_form()
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\sqladmin\models.py", line 1004, in scaffold_form
    return await get_model_form(
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\sqladmin\forms.py", line 580, in get_model_form
    field = await converter.convert(
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\sqladmin\forms.py", line 312, in convert
    converter = self.get_converter(prop=prop)
  File "C:\Users\akimg\.virtualenvs\projects-UdMq79XO\lib\site-packages\sqladmin\forms.py", line 266, in get_converter
    raise NoConverterFound(  # pragma: nocover
sqladmin.exceptions.NoConverterFound: Could not find field converter for column image (<class 'sqlalchemy_fields.types.image.ImageType'>).

### Environment

win11/Python3.10/sqladmin==0.10.2

Pipenv graph: 

alembic==1.10.3
  - Mako [required: Any, installed: 1.2.4]
    - MarkupSafe [required: >=0.9.2, installed: 2.1.2]
  - SQLAlchemy [required: >=1.3.0, installed: 2.0.9]
    - greenlet [required: !=0.4.17, installed: 2.0.2]
    - typing-extensions [required: >=4.2.0, installed: 4.5.0]
  - typing-extensions [required: >=4, installed: 4.5.0]
asyncpg==0.27.0
black==23.3.0
  - click [required: >=8.0.0, installed: 8.1.3]
    - colorama [required: Any, installed: 0.4.6]
  - mypy-extensions [required: >=0.4.3, installed: 1.0.0]
  - packaging [required: >=22.0, installed: 23.1]
  - pathspec [required: >=0.9.0, installed: 0.11.1]
  - platformdirs [required: >=2, installed: 3.2.0]
  - tomli [required: >=1.1.0, installed: 2.0.1]
fastapi-admin==1.0.4
  - aiofiles [required: Any, installed: 23.1.0]
  - aioredis [required: Any, installed: 2.0.1]
    - async-timeout [required: Any, installed: 4.0.2]
    - typing-extensions [required: Any, installed: 4.5.0]
  - Babel [required: Any, installed: 2.12.1]
  - bcrypt [required: Any, installed: 4.0.1]
  - fastapi [required: Any, installed: 0.95.1]
    - pydantic [required: >=1.6.2,<2.0.0,!=1.8.1,!=1.8,!=1.7.3,!=1.7.2,!=1.7.1,!=1.7, installed: 1.10.7]
      - typing-extensions [required: >=4.2.0, installed: 4.5.0]
    - starlette [required: >=0.26.1,<0.27.0, installed: 0.26.1]
      - anyio [required: >=3.4.0,<5, installed: 3.6.2]
        - idna [required: >=2.8, installed: 3.4]
        - sniffio [required: >=1.1, installed: 1.3.0]
  - jinja2 [required: Any, installed: 3.1.2]
    - MarkupSafe [required: >=2.0, installed: 2.1.2]
  - pendulum [required: Any, installed: 2.1.2]
    - python-dateutil [required: >=2.6,<3.0, installed: 2.8.2]
      - six [required: >=1.5, installed: 1.16.0]
    - pytzdata [required: >=2020.1, installed: 2020.1]
  - python-multipart [required: Any, installed: 0.0.6]
  - tortoise-orm [required: Any, installed: 0.19.3]
    - aiosqlite [required: >=0.16.0,<0.18.0, installed: 0.17.0]
      - typing-extensions [required: >=3.7.2, installed: 4.5.0]
    - iso8601 [required: >=1.0.2,<2.0.0, installed: 1.1.0]
    - pypika-tortoise [required: >=0.1.6,<0.2.0, installed: 0.1.6]
    - pytz [required: Any, installed: 2023.3]
  - uvicorn [required: Any, installed: 0.21.1]
    - click [required: >=7.0, installed: 8.1.3]
      - colorama [required: Any, installed: 0.4.6]
    - h11 [required: >=0.8, installed: 0.14.0]
FastAPI-SQLAlchemy==0.2.1
  - SQLAlchemy [required: >=1.2, installed: 2.0.9]
    - greenlet [required: !=0.4.17, installed: 2.0.2]
    - typing-extensions [required: >=4.2.0, installed: 4.5.0]
  - starlette [required: >=0.12.9, installed: 0.26.1]
    - anyio [required: >=3.4.0,<5, installed: 3.6.2]
      - idna [required: >=2.8, installed: 3.4]
      - sniffio [required: >=1.1, installed: 1.3.0]
httptools==0.5.0
httpx==0.24.0
  - certifi [required: Any, installed: 2022.12.7]
  - httpcore [required: >=0.15.0,<0.18.0, installed: 0.17.0]
    - anyio [required: >=3.0,<5.0, installed: 3.6.2]
      - idna [required: >=2.8, installed: 3.4]
      - sniffio [required: >=1.1, installed: 1.3.0]
    - certifi [required: Any, installed: 2022.12.7]
    - h11 [required: >=0.13,<0.15, installed: 0.14.0]
    - sniffio [required: ==1.*, installed: 1.3.0]
  - idna [required: Any, installed: 3.4]
  - sniffio [required: Any, installed: 1.3.0]
itsdangerous==2.1.2
jwt==1.3.1
  - cryptography [required: >=3.1,!=3.4.0, installed: 40.0.1]
    - cffi [required: >=1.12, installed: 1.15.1]
      - pycparser [required: Any, installed: 2.21]
mypy==1.2.0
  - mypy-extensions [required: >=1.0.0, installed: 1.0.0]
  - tomli [required: >=1.1.0, installed: 2.0.1]
  - typing-extensions [required: >=3.10, installed: 4.5.0]
Pillow==9.5.0
pre-commit==3.2.2
  - cfgv [required: >=2.0.0, installed: 3.3.1]
  - identify [required: >=1.0.0, installed: 2.5.22]
  - nodeenv [required: >=0.11.1, installed: 1.7.0]
    - setuptools [required: Any, installed: 65.5.0]
  - pyyaml [required: >=5.1, installed: 6.0]
  - virtualenv [required: >=20.10.0, installed: 20.21.0]
    - distlib [required: >=0.3.6,<1, installed: 0.3.6]
    - filelock [required: >=3.4.1,<4, installed: 3.11.0]
    - platformdirs [required: >=2.4,<4, installed: 3.2.0]
psycopg2==2.9.6
PyJWT==2.6.0
python-dotenv==1.0.0
python-socks==2.2.0
redis==4.5.4
  - async-timeout [required: >=4.0.2, installed: 4.0.2]
requests==2.28.2
  - certifi [required: >=2017.4.17, installed: 2022.12.7]
  - charset-normalizer [required: >=2,<4, installed: 3.1.0]
  - idna [required: >=2.5,<4, installed: 3.4]
  - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.15]
sqladmin==0.10.2
  - sqlalchemy [required: >=1.4, installed: 2.0.9]
    - greenlet [required: !=0.4.17, installed: 2.0.2]
    - typing-extensions [required: >=4.2.0, installed: 4.5.0]
  - starlette [required: Any, installed: 0.26.1]
    - anyio [required: >=3.4.0,<5, installed: 3.6.2]
      - idna [required: >=2.8, installed: 3.4]
      - sniffio [required: >=1.1, installed: 1.3.0]
  - wtforms [required: >=3,<4, installed: 3.0.1]
    - MarkupSafe [required: Any, installed: 2.1.2]
sqlalchemy-fields==0.4.0
  - sqlalchemy [required: >=1.4, installed: 2.0.9]
    - greenlet [required: !=0.4.17, installed: 2.0.2]
    - typing-extensions [required: >=4.2.0, installed: 4.5.0]
Telethon==1.28.5
  - pyaes [required: Any, installed: 1.6.1]
  - rsa [required: Any, installed: 4.9]
    - pyasn1 [required: >=0.1.3, installed: 0.4.8]
watchfiles==0.19.0
  - anyio [required: >=3.0.0, installed: 3.6.2]
    - idna [required: >=2.8, installed: 3.4]
    - sniffio [required: >=1.1, installed: 1.3.0]
websockets==11.0.2

**Comment by aminalaee** [comment]
Hi, you are correct.
This is a missing configuration, I can add it.
