### ISSUE TITLE
URLType field has no converter defined

### ISSUE THREAD

**Issue by dhait** [aminalaee/sqladmin#491]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When a URLType field is added to a model, "edit" on the record causes an exception:

    from sqlalchemy_fields.types import URLType

    class MyModel(Base):
        image_url = Column(URLType(255))
    ...

    sqladmin.exceptions.NoConverterFound: Could not find field converter for column image_url (<class 'sqlalchemy_fields.types.url.URLType'>).

### Steps to reproduce the bug

1. Create a model with a URLType field
2. Add a sqladmin ModelView for that model
3. Display the list of objects
4. Select the "edit" icon for the object

### Expected behavior

I would expect to see the default "Edit" view with the URL field editable

### Actual behavior

sqladmin.exceptions.NoConverterFound thrown

### Debugging material

Traceback (most recent call last):
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/sqladmin/authentication.py", line 60, in wrapper_decorator
    return await func(*args, **kwargs)
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/sqladmin/application.py", line 480, in edit
    Form = await model_view.scaffold_form()
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/sqladmin/models.py", line 1021, in scaffold_form
    return await get_model_form(
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/sqladmin/forms.py", line 586, in get_model_form
    field = await converter.convert(
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/sqladmin/forms.py", line 312, in convert
    converter = self.get_converter(prop=prop)
  File "/Users/dhait/PycharmProjects/divmax/venv/lib/python3.9/site-packages/sqladmin/forms.py", line 266, in get_converter
    raise NoConverterFound(  # pragma: nocover
sqladmin.exceptions.NoConverterFound: Could not find field converter for column image_url (<class 'sqlalchemy_fields.types.url.URLType'>).

### Environment

- MacOS / Python 3.9

**Comment by aminalaee** [comment]
You are right, this is missing. I will add it now, it's super simple

**Comment by dhait** [comment]
Awesome thank you
