### ISSUE TITLE
"Create" form fails when model has `meta` field

### ISSUE THREAD

**Issue by tcompa** [aminalaee/sqladmin#539]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When I include a model which has a `meta` field, this clashes with the `meta` field of the form object from wtforms.

I cannot immediately say whether this should be fixed in sqladmin or in wtforms (I can open the issue over there, if it's more appropriate), nor I could find an easy workaround.

Any advice is welcome.

### Steps to reproduce the bug

1. Install sqladmin (for instance from the current main, with `git clone` and then `pip install -e .`). This also installs wtforms (version 3.0.1).
2. Install fastapi (e.g. with `pip install fastapi[all]`, which is currently fetching version 0.99.1).
3. Prepare the following `main.py` script
```python
from sqlalchemy import Column, Integer, String, create_engine
from sqlalchemy.ext.declarative import declarative_base
from fastapi import FastAPI
from sqladmin import Admin, ModelView

Base = declarative_base()
engine = create_engine("sqlite:///example.db", connect_args={"check_same_thread": False})

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True)
    name = Column(String)
    meta = Column(String)   # NOTE: there is a `meta` field

Base.metadata.create_all(engine)  # Create tables

app = FastAPI()
admin = Admin(app, engine)

class UserAdmin(ModelView, model=User):
    column_exclude_list = [User.meta]

admin.add_view(UserAdmin)
```
5. Run the app with `uvicorn main:app`, and browse to `http://127.0.0.1:8000/admin/user/list`. This page correctly shows an empty list.
6. Click the "New user button". The browser will simply show a "Internal server error message", while the console will have a more detailed error traceback.

### Expected behavior

A model with a `meta` field can be handled by sqladmin+wtforms.

### Actual behavior

A model with a `meta` field cannot be handled by sqladmin+wtforms, due to the name clash with the `meta` attribute of the form object.

### Debugging material

When following the steps described above, the traceback reads
```python traceback
[...]
INFO:     127.0.0.1:35254 - "GET /user/create HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/somewhere/sqladmin/sqladmin/authentication.py", line 62, in wrapper_decorator
    return await func(*args, **kwargs)
  File "/somewhere/sqladmin/sqladmin/application.py", line 497, in create
    form = Form(form_data)
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/wtforms/form.py", line 286, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/somewhere/sqladmin/venv/lib/python3.10/site-packages/wtforms/form.py", line 106, in process
    formdata = self.meta.wrap_formdata(self, formdata)
AttributeError: 'StringField' object has no attribute 'wrap_formdata'
```

### Environment

Ubuntu 22, Python 3.10.6, sqladmin 978cdd6587c7fc8345076393ae6774cddbdcd48c (that is, version 0.13.0).

### Additional context

The wtforms `BaseForm` object is defined in https://github.com/wtforms/wtforms/blob/master/src/wtforms/form.py, and it clearly includes a `meta` attribute
```python
class BaseForm:
    """
    Base Form Class.  Provides core behaviour like field construction,
    validation, and data and error proxying.
    """

    def __init__(self, fields, prefix="", meta=_default_meta):
        """
        :param fields:
            A dict or sequence of 2-tuples of partially-constructed fields.
        :param prefix:
            If provided, all fields will have their name prefixed with the
            value.
        :param meta:
            A meta instance which is used for configuration and customization
            of WTForms behaviors.
        """
```

**Comment by aminalaee** [comment]
Hey,

I think you're right on track that this name clashes with WTForm,
You probably know that maybe you can work around this with `meta_ = Column("meta", String)`.

**Comment by tcompa** [comment]
Thanks for answering. I also discussed the same issue at wtforms (https://github.com/wtforms/wtforms/issues/791), and there seems to be no easy workaround that doesn't require a change of the field name.

I'm closing this issue as I don't think it has anything special to do with sqladmin.
