### ISSUE TITLE
Ckeditor <TypeError: Cannot convert undefined or null to object>

### ISSUE THREAD

**Issue by A-V-tor** [aminalaee/sqladmin#784]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Following the guide [sqladmin ckeditor](https://aminalaee.dev/sqladmin/cookbook/using_wysiwyg/) got an error:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ou.init (datacontroller.ts:344:42)
    at ou.<anonymous> (observablemixin.ts:277:33)
    at ou.fire (emittermixin.ts:241:31)
    at <computed> [as init] (observablemixin.ts:281:17)
    at classiceditor.ts:227:31
```

### Steps to reproduce the bug

Follow the ckeditor embedding documentation

### Actual behavior

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ou.init (datacontroller.ts:344:42)
    at ou.<anonymous> (observablemixin.ts:277:33)
    at ou.fire (emittermixin.ts:241:31)
    at <computed> [as init] (observablemixin.ts:281:17)
    at classiceditor.ts:227:31
```

### Environment

Sqladmin 0.17.0

### Additional context

Everything starts working fine if you add the following code 

```
<script src="https://cdn.ckeditor.com/ckeditor5/39.0.1/classic/ckeditor.js"></script>
<script>
    ClassicEditor
        .create(document.querySelector('#content'))
        .catch(error => {
            console.error(error);
        });
</script>
```
straight into the editor.html template before the last closing block, however I don't think this is the correct behavior.

**Comment by A-V-tor** [comment]
I don't know what it was, but it worked on its own after a while.
